# Generated by Django 5.0.1 on 2024-04-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotelbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite', models.CharField(choices=[('suite1', 'Standard'), ('suite2', 'Deluxe'), ('suite3', 'Joint'), ('suite4', 'Suite')], default='suite1', max_length=10)),
                ('people', models.CharField(choices=[('p1', '1 Person'), ('p2', '2 People'), ('p3', '3 People'), ('p4', '4 People')], default='p1', max_length=10)),
                ('numrooms', models.CharField(choices=[('1r', '1 room'), ('2r', '2 rooms'), ('3r', '3 rooms'), ('4r', '4 rooms')], default='1r', max_length=10)),
                ('checkin', models.DateField(default=None, null=True)),
                ('checkout', models.DateField(default=None, null=True)),
                ('email', models.EmailField(default=None, max_length=255, verbose_name='email address')),
            ],
        ),
    ]
