# Generated by Django 5.0.1 on 2024-04-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hotelbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket1', models.BooleanField(default=False)),
                ('ticket1num', models.IntegerField(default=0)),
                ('ticket2', models.BooleanField(default=False)),
                ('ticket2num', models.IntegerField(default=0)),
                ('ticket3', models.BooleanField(default=False)),
                ('ticket3num', models.IntegerField(default=0)),
                ('ticket4', models.BooleanField(default=False)),
                ('ticket4num', models.IntegerField(default=0)),
                ('date', models.DateField(default=None, null=True)),
                ('email', models.EmailField(default=None, max_length=255, verbose_name='email address')),
            ],
        ),
    ]
