# Generated by Django 5.0.1 on 2024-04-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tickbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbook',
            name='checkin',
            field=models.DateField(default=None, null=True, verbose_name='Check in date'),
        ),
        migrations.AlterField(
            model_name='hotelbook',
            name='checkout',
            field=models.DateField(default=None, null=True, verbose_name='Check out date'),
        ),
        migrations.AlterField(
            model_name='hotelbook',
            name='email',
            field=models.EmailField(default=None, max_length=255, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='hotelbook',
            name='numrooms',
            field=models.CharField(choices=[('1r', '1 room'), ('2r', '2 rooms'), ('3r', '3 rooms'), ('4r', '4 rooms')], default='1r', max_length=10, verbose_name='Number of Rooms'),
        ),
        migrations.AlterField(
            model_name='hotelbook',
            name='people',
            field=models.CharField(choices=[('p1', '1 Person'), ('p2', '2 People'), ('p3', '3 People'), ('p4', '4 People')], default='p1', max_length=10, verbose_name='Number of People'),
        ),
        migrations.AlterField(
            model_name='hotelbook',
            name='suite',
            field=models.CharField(choices=[('suite1', 'Standard'), ('suite2', 'Deluxe'), ('suite3', 'Joint'), ('suite4', 'Suite')], default='suite1', max_length=10, verbose_name='Suite Type'),
        ),
        migrations.AlterField(
            model_name='tickbooking',
            name='date',
            field=models.DateField(default=None, null=True, verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='tickbooking',
            name='email',
            field=models.EmailField(default=None, max_length=255, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='tickbooking',
            name='ticket1',
            field=models.BooleanField(default=False, verbose_name='Children (2 to 15 years)'),
        ),
        migrations.AlterField(
            model_name='tickbooking',
            name='ticket1num',
            field=models.IntegerField(default=0, verbose_name='Child tickets purchased'),
        ),
        migrations.AlterField(
            model_name='tickbooking',
            name='ticket2',
            field=models.BooleanField(default=False, verbose_name='Standard'),
        ),
        migrations.AlterField(
            model_name='tickbooking',
            name='ticket2num',
            field=models.IntegerField(default=0, verbose_name='Standard tickets purchased'),
        ),
        migrations.AlterField(
            model_name='tickbooking',
            name='ticket3',
            field=models.BooleanField(default=False, verbose_name='Off Peak Weekday'),
        ),
        migrations.AlterField(
            model_name='tickbooking',
            name='ticket3num',
            field=models.IntegerField(default=0, verbose_name='Off Peak tickets purchased'),
        ),
        migrations.AlterField(
            model_name='tickbooking',
            name='ticket4',
            field=models.BooleanField(default=False, verbose_name='Seniors'),
        ),
        migrations.AlterField(
            model_name='tickbooking',
            name='ticket4num',
            field=models.IntegerField(default=0, verbose_name='Senior tickets purchased'),
        ),
        migrations.AlterModelTable(
            name='hotelbook',
            table='Hotel Bookings',
        ),
        migrations.AlterModelTable(
            name='tickbooking',
            table='Ticket Bookings',
        ),
    ]
