# Generated by Django 5.0.1 on 2024-04-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_hotelbook_options_alter_tickbooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickbooking',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
