# Generated by Django 5.0.1 on 2024-04-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tickbooking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbook',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='hotelbook',
            name='numrooms',
            field=models.CharField(choices=[('1r', '1'), ('2r', '2'), ('3r', '3'), ('4r', '4')], default='1r', max_length=10, verbose_name='Number of Rooms'),
        ),
        migrations.AlterField(
            model_name='tickbooking',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
    ]
