# Generated by Django 5.0.1 on 2024-04-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='UserPoints',
        ),
    ]
