# Generated by Django 5.0.1 on 2024-04-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_myuser_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='active',
            new_name='is_active',
        ),
    ]
